name: Keep Azure SQL Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Ejecuta cada 10 minutos
  workflow_dispatch:

jobs:
  keep-db-alive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sqlcmd
      run: |
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl -sSL https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install mssql-tools unixodbc-dev

    - name: Verify connection to Azure SQL
      run: sqlcmd -S tcp:inventorysystemacg.database.windows.net,1433 -U ${{ secrets.DB_USERNAME }} -P ${{ secrets.DB_PASSWORD }} -d DB_inventorySystem -Q "SELECT 1"
